name: Delivery

on:
  push:
    tags:
      - 'WEEK*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Delivery
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Set up JDK 1.17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
#       - name: Run Mutation Testing
#         run: mvn verify -Ppit
#       - name: Publish Artifact
#         uses: actions/upload-artifact@v3
#         with:
#           name: resulats PIT
#           path: reports/pit
#           if-no-files-found: error
      - name: Discord Notification Delivered
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          webhook: "https://discordapp.com/api/webhooks/956068061100789801/SB4rQKVAuiGBeeT3ptjPc6zY-AzeUQG_FaKYDdvdU7M_0CitvtDgs8UIvhiB9gQ5w6KX"
          title: "Rendu QGL"
          description: "All good, le tag est posé ! Les rapports sont dans l'artefact"
          color: 0xff91a4
          nodetail: true
      - name: Discord Notification Delivered
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          webhook: "https://discordapp.com/api/webhooks/956068061100789801/SB4rQKVAuiGBeeT3ptjPc6zY-AzeUQG_FaKYDdvdU7M_0CitvtDgs8UIvhiB9gQ5w6KX"
          title: "Rendu QGL"
          description: "C'est la merde, il y a un probleme sur les tests ! Les rapports sont dans l'artefact"
          color: 0xff91a4
          nodetail: true
      - name: Slack Notification sended
        uses: slackapi/slack-github-action@v1.18.0
        if: ${{ success() }}
        with:
         channel-id: 'si3-qgl-21-22-kihm'
          # For posting a simple plain text message
         slack-message: "Message Test ! Désolé pour le derangement \nTag posé, les rapports sont dans l'artefact"
        env:
          SLACK_BOT_TOKEN: 'xoxb-744038435863-3300487232753-wYJg4NbvL9nkleJskfkdKaAe'
