name: PR closed

on:
  pull_request:
    types: [review_request_removed,edited,synchronize]
  pull_request_review:
    types: [subitted, edited]
  check_suite:
    types: [completed]
jobs:
    build:
      runs-on: ubuntu-latest
      name: Delivery
      steps:
      - id: automerge
        name: Merge pull request
        uses: "pascalgn/automerge-action@v0.15.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          LOG : "TRACE"
          MERGE_LABELS: "!wait"
          MERGE_REMOVE_LABELS: "wait"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "Auto merge {pullRequest.number}"
          MERGE_FORKS: false
          MERGE_RETRY_SLEEP: "10000"
          MERGE_REQUIRED_APPROVALS: 0
          MERGE_DELETE_BRANCH: true
          MERGE_ERROR_FAIL: true
          UPDATE_LABELS: ""      
      - name: Close involved issue  
        uses: Logerfo/close-action@0.0.1
        if: ${{steps.automerge.outputs.mergeResult == "merged" }}
        with:
         github-token: ${{ secrets.GITHUB_TOKEN }} # The `GITHUB_TOKEN` secret.
         comment: true # If `true`, will comment on the closing issue(s).
