name: PR closed

on:
  pull_request:
    types: [ closed ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Clean Project
    steps:
      - name: Remove merged branch
        uses: zjutszl/delete-merged-branch-asdf@master
      - name: Close involved issue
        uses: Logerfo/close-action@0.0.1
        
